blog/urls.py
from django.urls import path, include
from . import views

app_name='blog'

urlpatterns = [
    path('', views.post_list, name='post_list' ),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    #path('', views.index, name="index"),
    path('', include('main.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post
from django.utils import timezone
from .form import PostForm

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, pk):
    post=get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post':post})

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)    
    else:        
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)    
    else:        
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q, Count

from ..models import Question

def index(request):
    
    #페이지를 얻어옴
    page = request.GET.get('page', '1') 
    
    # 검색어를 얻어옴
    kw = request.GET.get('kw', '') 
    
    # 정렬 기준
    so = request.GET.get('so', 'recent')
    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')
        
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()
    

    
    #페이지 처리
    paginator = Paginator(question_list, 10) #페이지당 10개씩 보여주기.
    page_obj = paginator.get_page(page)
    
    context = { "question_list" : page_obj, 'page': page, 'kw': kw, 'so' : so }
    
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = { 'question' : question }
    
    return render(request, 'pybo/question_detail.html', context)

templates/blog/base.html
{% extends 'base.html' %}
{% comment %} <!DOCTYPE html>
<html lang="ko">
    <head> {% endcomment %}
        {% block tilte %}Django Girls blog{% endblock %}
        {% comment %} <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css"> {% endcomment %}
    {% comment %} </head>
    <body> {% endcomment %}
        
        {% comment %} <div class="page-header header-font">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <h1><a href="/blog/">Django Girls Blog</a></h1>
        </div> {% endcomment %}

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content%}
                    {% endblock %}
                </div>
            </div>
        </div>
    {% comment %} </body>
</html> {% endcomment %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content%}
    <h1>new Post</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
{% for post in posts %}
    <div class="post">
        <div class="date">
            <p>published: {{ post.published_date }}</p>
        </div>
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endfor %}
{% endblock %}